/* Shared lookups: country/region -> flag asset, and display names for areas
   and secondary areas. Extracted from src/layout.js so both the mobile page
   (src/mobile.js) and the legacy radial page (src/layout.js) use one copy. */
const iso={Algeria:"dz",Angola:"ao",Argentina:"ar",Australia:"au",Austria:"at",Bangladesh:"bd",Belgium:"be",Belize:"bz",Brazil:"br",Cameroon:"cm",Canada:"ca",China:"cn",Colombia:"co",Cuba:"cu","Czech lands":"cz",Czechia:"cz","DR Congo":"cd",Denmark:"dk",Dominica:"dm","Dominican Republic":"do",Egypt:"eg",Ethiopia:"et",Finland:"fi",France:"fr",Gambia:"gm",Germany:"de",Ghana:"gh",Greece:"gr",Guadeloupe:"gp",Guatemala:"gt",Haiti:"ht",Honduras:"hn","Hong Kong":"hk",India:"in",Indonesia:"id",Ireland:"ie",Israel:"il",Italy:"it","Ivory Coast":"ci",Jamaica:"jm",Japan:"jp",Kenya:"ke",Korea:"kr",Laos:"la",Malaysia:"my",Mali:"ml",Martinique:"mq",Mauritius:"mu",Mexico:"mx",Mongolia:"mn",Morocco:"ma",Netherlands:"nl","New Zealand":"nz",Niger:"ne",Nigeria:"ng",Norway:"no",Pakistan:"pk",Panama:"pa",Peru:"pe",Philippines:"ph",Portugal:"pt","Puerto Rico":"pr","Republic of the Congo":"cg",Romania:"ro",Russia:"ru","Réunion":"re",Scotland:"gb",Senegal:"sn",Serbia:"rs","Sierra Leone":"sl","South Africa":"za","South Korea":"kr",Spain:"es",Sweden:"se",Tanzania:"tz",Thailand:"th","Trinidad and Tobago":"tt",UK:"gb",USA:"us","United Kingdom":"gb","United States":"us",Uruguay:"uy",Zambia:"zm",Zimbabwe:"zw"};
const regions=new Set(["Africa","Caribbean","Europe","Latin America","Middle East","Scandinavia","South Asia","West Africa"]);
const regionIcons={Europe:["assets/flags/eu.svg","Europe"],Africa:["assets/flags/africa.svg","Africa"],"West Africa":["assets/flags/africa.svg","West Africa"],"South Asia":["assets/flags/asia.svg","South Asia"],Caribbean:["assets/flags/caribbean.svg","Caribbean"],"Latin America":["assets/flags/latinamerica.svg","Latin America"]};function flagAssets(s){const out=[];for(const raw of (s||"").split(","))for(const bit of raw.trim().split("/")){const v=bit.trim();if(!v)continue;if(regionIcons[v]){out.push([regionIcons[v][0],regionIcons[v][1],""]);continue}if(regions.has(v))continue;if(v==="Worldwide")out.push(["assets/symbols/worldwide.svg",v,"symbol"]);else if(v.toLowerCase()==="online")out.push(["assets/symbols/online.svg","Online","symbol"]);else if(iso[v])out.push(["assets/flags/"+iso[v]+".svg",v,""])}return out}
const areaDisplay={rock:"Rock",rasta:"Rasta / Reggae",folk:"Folk",hiphop:"Hip Hop",metal:"Metal",breakbeat:"Breakbeat",latin:"Latin",pop:"Pop",house:"House",african:"African",soulful:"Soul / R&B",classical:"Classical",experimental:"Experimental",hardcore:"Hardcore",jazz:"Jazz",techno:"Techno",jamaican:"Jamaican",psy:"Psytrance",industrial:"Industrial",trance:"Trance",chiptune:"Chiptune",downtempo:"Downtempo"};
const secondaryDisplay={african:"African",ambient:"Ambient",american:"American",asian:"Asian",black:"Black Metal",breakbeat:"Breakbeat",breaks:"Breaks",chiptune:"Chiptune",death:"Death Metal",dnb:"Drum & Bass",downtempo:"Downtempo",dubstep:"Dubstep",european:"European",idm:"IDM",latin:"Latin",noise:"Noise",oceanian:"Oceanian",psy:"Psytrance",punk:"Punk",sampling:"Sampling",ukgrime:"UK Grime"};
function secondaryLabel(k){return secondaryDisplay[k]||(k?k.charAt(0).toUpperCase()+k.slice(1):"");}
